baseURL: 'https://donaldh.wtf/'
languageCode: en-uk
title: donaldh.wtf
theme: beautifulhugo
params:
  subtitle: Hacks and Misadventures
  highlight: true
  rss: true
  topmenu: categories
markup:
  highlight:
    noClasses: false
permalinks:
  post: '/:year/:month/:slug/'
author:
  name: Donald Hunter
  github: donaldh
  twitter: donaldhunter
  stackoverflow: 'users/386025'
  instagram: donaldihunter
  flickr: sealgair
menu:
  main:
    - name: About
      url: about/
      weight: 3
    - name: Now
      url: now/
      weight: 2
    - name: Tags
      url: tags
      weight: 1
    - name: Categories
      url: categories
      weight: 1
paginate: 20
