#+title: what I'm doing now
#+date: 2024-11-02

* This Week

I am still [[/2024/07/a-new-keyboard/][learning to type]] again. It turns out that the switch from an ISO layout back to ANSI
after 20 odd years is causing me grief. My newlines often get a ~\~ mixed in and tilde is 3 rows
higher than expected.

* Recently

I spent some time avoiding Emacs package bankruptcy. A recent package install broke [[https://magit.vc][Magit]] so I
decided it was time to update all installed packages and prune out all the things I no longer
use.

I also turned on ~which-key-mode~ to help discoverability. I've been using Emacs for decades but
there is plenty I have not learned about yet. The gem I learned this week is the ~C-x 8 e~ emoji
keymap.

* Zero Trust

Having spent the last 20+ years focused on networking technologies, I am now enjoying a bit of a
pivot to Zero Trust architectures. Sure, there's still a lot of networking in Zero Trust, but
there's also some interesting new problems related to identity and attestation as well as the
need for compliance auditing and maturity assessment.
